name: auscy
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.1.0
  google_generative_ai: ^0.4.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconly: ^1.0.1  
  image_picker: ^1.1.2
  intl: ^0.17.0
  mime: ^1.0.5
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  toast: ^0.3.0
  uuid: ^4.4.2
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
