name: auscy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^6.1.1
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  deepgram_speech_to_text: ^3.0.3
  file_picker: ^8.3.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.9.3
  flutter_sound_record: ^3.3.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.10+1
  google_generative_ai: ^0.4.5
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: null
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  mime: ^2.0.0
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  record: ^5.2.0
  top_snackbar_flutter: ^3.1.0
  uuid: ^4.4.2
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.0

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svg/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
